ДЗ 1
Su9DenLY/2024-2-VK-EDU-Frontend-K-Terebaev pull request #1
Opened 2024-09-19 18:22 UTC by Su9DenLY

# Домашнее задание № 1

Прошу @martinkomitsky, @haseprogram, @kgrechin
Что было сделано:
1) Реализовал функции correctSentence, nonUniqueElements, convertBytesToHuman;
2) Написал unit-тесты для функции convertBytesToHuman;

2024-09-19 18:29 UTC, kgrechin requested changes

2024-09-19 18:29 UTC, kgrechin commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman([1, 2, 3, 4, 5])).toBe(false)
добавь тестов на NaN, null, undefined

2024-09-19 18:29 UTC, kgrechin commented on nonUniqueElements.js
> +  const map = new Map();
Map больше памяти занимает чем обычный обьект, тут можно его использовать, прост рекомендация, можешь поправить сейчас или к следующему дз, или не поправлять

2024-09-19 18:29 UTC, kgrechin commented on correctSentence.js
> +export default function correctSentence(text) {
добавь проверку и тесты, что входной аргумент строка, если нет - пусть возвращает пустую строку

2024-09-19 21:56 UTC, Su9DenLY commented on nonUniqueElements.js
> +  const map = new Map();
Map же, вроде, работает быстрее. Понятно, что тут маленькие значения, но все же. Разве скорость не важнее затрат по памяти?

2024-09-20 05:21 UTC, kgrechin commented on nonUniqueElements.js
> +  const map = new Map();
вставка и получение и там и там o(1), мапа позволяет использовать клбчи разных типов данных

а также сохраняет порядок вставки, то есть допустим при итерации, порядок будет такой в каком добавляли, в то время как объект может сортировать ключи

2024-09-20 05:22 UTC, kgrechin commented on nonUniqueElements.js
> +  const map = new Map();
в данном случае конечно, разница в памяти будет не столь велика, храним просто чиселки

2024-09-20 13:39 UTC, Su9DenLY commented
1) Добавил тесты на NaN, null, undefined для функции convertBytesToHuman
2) Поменял Map на объект
3) В функции correctSentence добавил проверку на то, что входным аргументом является строка

2024-09-20 14:40 UTC, Su9DenLY commented
Еще провел замеры времени исполнения вставки, поиска и удаления в Map и Object.
Код для Map
`
const mapStart = performance.now();
const myMap = new Map()
const mapSize = 10000000

for (let i = 0; i < mapSize; i++) {
    myMap.set(i, i)
}
for (let i = 0; i < mapSize; i++) {
    myMap.get(i)
}
for (let i = 0; i < mapSize; i++) {
    myMap.delete(i)
}
console.log(`Map execution time: ${performance.now() - mapStart} milliseconds`)
` 

Код для Object
`
const objStart = performance.now();
const myObj = {}
const objSize = 10000000

for (let i = 0; i < objSize; i++) {
    myObj[i] = i
}
for (let i = 0; i < objSize; i++) {
    const val = myObj[i]
}
for (let i = 0; i < objSize; i++) {
    delete myObj[i]
}
console.log(`Object execution time: ${performance.now() - objStart} milliseconds`)
`

Результаты получились такие
Map execution time: 3553.687184 milliseconds
Object execution time: 531.9463780000005 milliseconds

2024-09-20 15:31 UTC, kgrechin approved these changes

2024-09-20 15:32 UTC, kgrechin commented
от меня аппрув, @martinkomitsky, @HaseProgram

2024-09-21 17:33 UTC, martinkomitsky approved these changes
12!

2024-09-21 17:33 UTC, merged