ДЗ 2
Su9DenLY/2024-2-VK-EDU-Frontend-K-Terebaev pull request #2
Opened 2024-09-26 22:22 UTC by Su9DenLY

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin проверить его.

Что было сделано:
1) Перенес файлы первого домашнего задания в папку homework1;
2) Сверстал сайт по макету, написал стили;
3) Реализовал хранение сообщений в localStorage и отправку сообщений при нажатии Enter, поле ввода при этом очищается;
4) Добавил проверку сообщения, чтобы оно не было пустым. Новые сообщения появляются снизу. В момент отправки сообщения страница автоматически прокручивается вниз. При большом количестве сообщений появляется скролл. Есть возможность ставить Enter, внутри сообщение комбинацией клавиш Shift+Enter, высота поля ввода при этом изменяется.

2024-09-29 11:04 UTC, kgrechin requested changes

2024-09-29 11:04 UTC, kgrechin commented on simple-chat/src/index.js
> +            ${messageItem.username}
для просто текста лучше использовать innerText

2024-09-29 11:04 UTC, kgrechin commented on simple-chat/src/index.js
> +        event.preventDefault()
надо запревентить дефолтное поведение для отправки сразу, сейчас если нажать то будет рефреш страницы

2024-09-29 11:04 UTC, kgrechin commented on simple-chat/src/index.js
> +        if (index === 0) {
наверное лучше запомнить ref элемента или накидывать какой-нибудь аттрибут и после цикла делать ref.scrollIntoView()

2024-09-29 11:04 UTC, kgrechin commented on simple-chat/src/index.js
> +    messages.reverse().forEach((messageItem, index) => {
что думаешь насчет того, чтобы не делать каждый раз реверс, а использовать css для этого flex-reverse?

2024-09-29 11:04 UTC, kgrechin commented on simple-chat/src/index.js
> +    } while (currentDate - date < milliseconds);
интересное решение)) но лучше воспользоваться Promise с setTimeout

2024-09-29 11:04 UTC, kgrechin commented on simple-chat/src/index.js
> +const form = document.querySelector('form');
вообще было бы круто если бы localStorage использовался только при первом маунте для считывания сохраненных и при анмаунте для сохранения, а в момент использования мы бы работали с локальным стейтом, что было бы куда лучше, чем каждый раз перезаписывать LS

2024-09-29 12:36 UTC, Su9DenLY commented on simple-chat/src/index.js
> +    messages.reverse().forEach((messageItem, index) => {
Ну вообще у меня стоит flex-direction: column-reverse, чтобы первые сообщения были снизу экрана. Но из-за этого  новые сообщения попадают выше старых. Из-за этого у меня стоит reverse для массива, чтобы старые сообщения были раньше и попадали выше новых. Я пытался сделать это через justify-content: end, но он ломает overflow: область с сообщениями просто не скроллится

2024-09-29 12:37 UTC, Su9DenLY commented on simple-chat/src/index.js
> +    } while (currentDate - date < milliseconds);
А у меня и стоит setTimeout. Это я просто экспериментировал и забыл удалить функцию. Она там нигде не используется

2024-09-29 20:08 UTC, Su9DenLY commented
1) Поменял innerHTML на innerText, там где было необходимо;
2) Запревентил дефолтное поведение для отправки сразу. Обновления по нажатию на кнопку нет;
3) Перенес scrollIntoView. Убрал перерендеривание после отправки каждого сообщения;
4) Удалил функцию sleep;
5) Сделал так, чтобы сообщения сохранялись в localStorage только при перезагрузке страницы или выходе с нее.

2024-09-30 04:53 UTC, kgrechin requested changes

2024-09-30 04:53 UTC, kgrechin commented on simple-chat/src/index.js
> +    messageContent.innerHTML = `<div>${text.replace(/\n/g, '<br>')}</div>`;
сейчас сюда можно записать любой HTML код введя его в инпут

2024-09-30 04:53 UTC, kgrechin commented on simple-chat/src/index.js
> +        messageContainer.scrollIntoView({behavior: 'smooth'});
нужна ли подкрутка через js к последнему сообщению? 

я это вижу как-то так:

<img width="368" alt="Снимок экрана 2024-09-30 в 07 52 30" src="https://github.com/user-attachments/assets/df221599-c0bc-4535-b671-5962c9f25f80">

скролл будет нативный и не надо будет подкручивать его чяерез js

2024-09-30 15:43 UTC, Su9DenLY commented
1) Добавил обработку текста в инпуте на код HTML

2024-09-30 17:24 UTC, kgrechin requested changes

2024-09-30 17:24 UTC, kgrechin commented on simple-chat/src/index.js
> +    messageContent.innerHTML = `<div>${escapeHTML(text).replace(/\n/g, '<br>')}</div>`;
здорово, что написал escape, но тут скорее надо просто превращать в текст все что введет пользователь:

  ```
const a = document.createElement('div');
  a.innerText = text;
  messageContent.appendChild(a);
```

2024-09-30 17:24 UTC, kgrechin commented on simple-chat/src/index.js
> +    messageContent.innerHTML = `<div>${escapeHTML(text).replace(/\n/g, '<br>')}</div>`;
unsespaceHTML можешь оставить

2024-09-30 17:24 UTC, kgrechin commented on simple-chat/src/index.scss
> +  height: 6%;
поменяй на не относительные единицы, допустим 60px;

2024-09-30 17:24 UTC, kgrechin commented on simple-chat/src/index.html
> +            <button class="button-white">
забыл добавить, в рамках дз надо сделать чтобы и слева и справа были сообщения, которые берутся из LS

2024-09-30 19:12 UTC, Su9DenLY commented
1) Поменял innerHTML на innerText для текста сообщения;
2) Поменял высоту header'а на неотносительные единицы;
3) Добавил сообщения от собеседника.

2024-10-02 05:57 UTC, kgrechin approved these changes
@HaseProgram, @martinkomitsky, от меня аппрув

2024-10-02 21:01 UTC, HaseProgram approved these changes
Супер, 12!

2024-10-02 21:01 UTC, merged