ДЗ 7
Su9DenLY/2024-2-VK-EDU-Frontend-K-Terebaev pull request #7
Opened 2024-11-21 23:42 UTC by Su9DenLY

# Домашнее задание №7

Прошу @martinkomitsky, @haseprogram, @kgrechin проверить его.

Что было сделано:
1) Проект использует backend(Polling);
2) Добавил регистрацию;
3) Реализовано: 
	1) Создание чатов;
	2) Поиск по чатам и по пользователям;
	3) Отправка и получение сообщений;
	4) Возможность смотреть и изменять свой профиль.

2024-11-22 00:03 UTC, Su9DenLY commented
https://github.com/user-attachments/assets/15b6087d-32e5-4472-8dcc-9179611c4cec

2024-11-23 10:01 UTC, kgrechin requested changes
@Su9DenLY, в целом все хорошо)

напиши пожалуйста мне в твоем менеджере (kgrechin), чтобы я зашел и смог тебе ответить)

по поводу хедера - попробуй установить ему position: sticky или position: fixed

2024-11-23 10:08 UTC, Su9DenLY commented
@kgrechin написал

2024-11-23 10:27 UTC, kgrechin commented
7 баллов получается( такая жизнь

2024-11-23 10:28 UTC, kgrechin approved these changes

2024-11-23 10:47 UTC, merged